spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/matcher
    password: 123
    username: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
servlet:
  multipart:
    enabled: true
    max-request-size: 20MB
    max-file-size: 20MB
