spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/matcher
    password: 54321
    username: postgres
servlet:
  multipart:
    enabled: true
    max-request-size: 20MB
    max-file-size: 20MB
